export * from './base-icon/base-icon.component';
export * from './icon-close/icon-close.component';
export * from './icon-dot-vertical/icon-dot-vertical.component';
export * from './icon-eye/icon-eye.component';
export * from './icon-login/icon-login.component';
export * from './icon-logout/icon-logout.component';
export * from './icon-pencil/icon-pencil.component';
export * from './icon-trash/icon-trash.component';
export * from './icons.module';